name: Generate Metrics

on:
  schedule: # 매일 6시에 자동 실행
    - cron: "0 6 * * *"
  workflow_dispatch: # 수동 실행

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: rlaxogh76 # 자신의 GitHub 유저네임으로 변경
